christoph-fricke/openapi-msw

- .changeset/perfect-mangos-grow.md
- package.json
Adds supports for tools that do not understand `exports` fields in the package.json file.
> fix: support older tools with legacy entrypoint definitions

- .prettierignore
- CHANGELOG.md
Formatting the changelog with "proseWrap: always" appears to cause bad line breaks in GitHub releases.
> chore: stop formatting the changelog

- CHANGELOG.md
The latest release was still based on a branch that formatted the changelog, thus reverting all the previous changes. This PR reverts it again.
> chore: reset changelog formatting

- .changeset/big-coats-tan.md
- src/type-helpers.ts
- tsconfig.build.json
- tsconfig.json
This PR fixes #16 by remapping generated `never` responses to `null`. That has the nice effect that only strict responses that return `null` can be returned. Mapping to `undefined` would allow any response.
So if an endpoints changes from having a response content to no-content, it results in a conflict in the handler and is not silently accepted.
> fix: "empty response" handlers cannot return a response

- .prettierignore
- .prettierrc.json
This PR reverts previous attempts to ignore "proseWrap" for changelog files, which still didn't work and still caused weirdly formatted GitHub releases. Instead, it applies the solution discovered by Paul Hachmang in this comment: https://github.com/changesets/changesets/issues/774#issuecomment-1064996654
> chore: fix prose-wrap in changelog files

- .changeset/eighty-ads-remain.md
- tsconfig.build.json
fixes "Failed to parse source map from 'node_modules\openapi-msw\exports\main.ts'" error when serving with vite
> fix: include sources in source map

- .changeset/tame-eyes-complain.md
- src/type-helpers.ts
- test/fixtures/path-fragments.api.yml
- test/no-content.test-d.ts
- test/path-fragments.test-d.ts
- test/path-fragments.test.ts
- test/request-body.test-d.ts
- test/response-content.test-d.ts
This PR changes the typing for the `params` to convert all path fragments to string. In case a fragment is a string literal type, the literal gets preserved. This fixes #22.
> fix(path): fragment types are not compatible with string runtime type

- .prettierrc.json
- package-lock.json
- package.json
- src/openapi-http.test.ts
- src/path-mapping.test.ts
- vitest.config.ts
This PR adds [prettier-plugin-organize-imports](https://www.npmjs.com/package/prettier-plugin-organize-imports) to sort imports in the same fashion as VS Code when code is formatted.
> chore: sort imports during formatting

- .changeset/smart-crabs-deliver.md
- src/api-spec.ts
- test/fixtures/query-params.api.yml
- test/query-params.test-d.ts
This fixes endpoints with no specified query params. Previously, the would accept any query key. However, it is more helpful if they accept no query key at all.
closes #43
> fix: endpoints with no query params should not allow any query key

- .changeset/sharp-rivers-rescue.md
- src/api-spec.ts
- src/type-utils.ts
- test/fixtures/no-content.api.yml
- test/fixtures/response-content.api.yml
- test/no-content.test-d.ts
- test/response-content.test-d.ts
This PR changes how response bodies are mapped. Previously, it should have chosen the first 2XX status code with the first media type, according to the JSDocs from `openapi-typescript-helpers`. However, the JSDocs comments are a lie as the types pick the union of all 2XX responses with all media types. This causes problems with specs where different media types are used across multiple status codes (see the following example). It results in a response typing of `StrictResponse<null>` instead of `StrictResponse<{ /* ... */} | string>`.
```yaml
/resource:
get:
summary: Get Resource
operationId: getResource
responses:
200:
description: Success
content:
application/json:
schema:
$ref: "#/components/schemas/Resource"
202:
description: Accepted
content:
text/plain:
schema:
type: string
```
With …
> feat: include all status code and media types in response body union

- .changeset/tasty-roses-walk.md
- README.md
- src/api-spec.ts
- src/http-status-wildcard.ts
- src/response-resolver.ts
- src/response.ts
- test/fixtures/response-content.api.yml
- test/response-content.test-d.ts
- test/response-content.test.ts
Missing stuff / Open questions are marked with "TODO" in the source code.
> feat: add `response` helper to resolver info

- .changeset/perfect-pans-pump.md
- src/api-spec.ts
- src/request.ts
- src/response-resolver.ts
- test/fixtures/request-body.api.yml
- test/request-body.test-d.ts
Add a new typing for the `request` object, which infers the `.json()` and `.text()` typings from defined media types. Previously, a union of all media types where used for the return-type of `.json()`.
closes #40
> feat: enhanced request object typing

- .changeset/real-carpets-rhyme.md
- src/response.ts
- test/response-content.test.ts
This PR updates `response(...).empty()` to set the `content-length` header to 0 by default if the header is not provided explicitly. Other response factories already set the header as they delegate to MSW, which sets the header already.
closes #56
> feat(response): set content-length header for empty response

- .husky/pre-commit
- .lefthook.yml
- package-lock.json
- package.json
This PR replaces husky and lint-staged with [lefthook](https://github.com/evilmartians/lefthook). Apart from being more powerful and requiring less dependencies, this also fixes a race-condition in the current hook setup.
Previously automated fixes applied by ESLint would not be formatted with Prettier. With lefthook, the lint command is configured to be run before formatting to ensure that all code changes will be correctly formatted.
> chore: replace husky and lint-staged with lefthook

- .changeset/kind-dancers-return.md
- src/request.ts
- src/response.ts
- src/type-utils.ts
- test/fixtures/request-body.api.yml
- test/fixtures/response-content.api.yml
- test/request-body.test-d.ts
- test/response-content.test-d.ts
This PR fixes a problem with type inference for extended json mime types, such as `application/problem+json`. Previously OpenAPI-MSW would not catch such mime-types and would infer that an endpoint should not receive or return JSON. Thus `response(...).json` would be typed as `never`. Now, it will be typed with the proper JSON response.
> fix: proper type inference for extended json mime types

- .changeset/eight-feet-heal.md
- package-lock.json
- package.json
- src/api-spec.ts
- src/request.ts
- src/response.ts
- src/type-utils.ts
We were relying on an oder version of this dependency without being able to easily update. by removing it, we were able to simplify the `RequestMap` type, which previously relied on it.
> refactor: remove openapi-typescript-helpers dependency

- .changeset/eight-feet-heal.md
- .changeset/nasty-peaches-applaud.md
- .changeset/twenty-tables-allow.md
- exports/main.ts
- package-lock.json
- package.json
- src/openapi-http.ts
- src/response-resolver.ts
This updates the peer dependency on MSW to its latest version. With this change we can benefit from some newly exposed types.
It is a small breaking change and thus causes a major release.
> feat!: update msw peer dependency to latest version

- .changeset/angry-feet-dance.md
- src/request.ts
- test/request-body.test-d.ts
This PR adds a small adjustment to the `OpenApiRequest` type to return the type-safe request typing when `Request.prototype.clone` is called. With this cloned requests remain strict typed and do not loose their type safety.
> feat(request): add override for cloned request to remain type-safe

- .changeset/fifty-groups-judge.md
- README.md
- exports/main.ts
- src/openapi-http-utilities.ts
- test/fixtures/.redocly.yml
- test/fixtures/http-utilities.api.yml
- test/http-utilities.test-d.ts
This PR adds and exposes utility types for extracting information from requests handlers. Exposed types are:
- `PathsFor`
- `RequestBodyFor`
- `ResponseBodyFor`
closes #75
> feat: add http utility types

- .changeset/puny-places-fall.md
- src/openapi-http-utilities.ts
- src/openapi-http.ts
- src/path-mapping.ts
- src/response-resolver.ts
Updated the TSDOC comments to display code examples in VS Code for response helpers.
> feat: rendered code examples for resolver helpers

- .changeset/poor-trams-take.md
- package.json
- tsconfig.build.json
This enables proper "Go To Definition" support in editors—jumping directly to the TypeScript source file instead of the declaration file.
> feat: output declaration maps for proper jump-to-source support

- .changeset/wise-roses-cheer.md
- package-lock.json
- package.json
- src/openapi-http.test.ts
- src/path-mapping.test.ts
- src/response.ts
- test/http-methods.test-d.ts
- test/http-utilities.test-d.ts
- test/no-content.test-d.ts
- test/no-content.test.ts
- test/options.test.ts
- test/path-fragments.test-d.ts
- test/path-fragments.test.ts
- test/query-params.test-d.ts
- test/query-params.test.ts
- test/request-body.test-d.ts
- test/request-body.test.ts
- test/response-content.test-d.ts
- test/response-content.test.ts
The compatibility pipeline has been failing for a few weeks with broken type tests. Only the tests has been effected and no actual usage with later MSW versions. They were a bit too relying and MSW's internal typing.
To finally address this, this PR has to bump the MSW requirement and overhaul the test suite to rely less on internal MSW typing. Namely the return type of response resolvers is now checked with the first level type `AsyncResponseResolverReturnType` and not the transitive `HttpResponse`, which broke with the latest MSW versions.
> refactor!: bump MSW peer dependency and overhaul failing test suite
